version: '3'

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: basket-api
    ports:
      - "3001:80"
    networks:
      - basket

  frontend:
    image: nginx:alpine
    container_name: basket-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/:/usr/share/nginx/html
    networks:
      - basket

networks:
  basket: