version: '3'

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: basket-api
    ports:
      - "3001:80"
    networks:
      - basket

networks:
  basket: